import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Canvas ,useLoader} from '@react-three/fiber'
import { Suspense, useState,useRef } from 'react'
import { OrbitControls,Text3D ,Text,useTexture,RoundedBox} from "@react-three/drei"
import TextureLoader from "three/src/loaders/TextureLoader"
import fontUrl from './Digital-7_Regular.json'
// import color1 from "./colorTexture.png"
 
const inter = Inter({ subsets: ['latin'] })


export default function Home() {

const ref=useRef();

  var arr=[];
const [current,setCurrent]=useState("");
const [prev,setPrev]=useState("");
const [operator,setOperator] =useState("")
const [result,setResult]=useState("")

const handleInput=(e)=>{
  if(e ==="." && current.includes("."))
    return;

    if(!current && !operator){
      setPrev(prev+e);
    }else{
      setCurrent(current+e)
    }
  
 
}
const handleOperator =(e)=>{
 setOperator(e)
 console.log(e)
}
const calculate=()=>{
  let cal;
  switch (operator) {
    case "+" :
    cal= String(parseFloat(prev) + parseFloat( current))  
      break;
      case "-" :
        cal= String(parseFloat(prev) - parseFloat( current))  
        break;
         case "*" :
        cal= String(parseFloat(prev) * parseFloat( current))  
        break;
         case "/" :
        cal= String(parseFloat(prev) / parseFloat( current))  
        break;
  }
  setResult(cal)
}
const reset =()=>{
  setCurrent("")
  setOperator("")
  setPrev("")
  setResult("")
}
  return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Canvas>
          <Suspense fallback={null}>
            <OrbitControls />
            <ambientLight intensity={0.1} />
            <spotLight args={["white",0.8,12,Math.PI/180*120 ,0.8]} position={[2,1,2]}/>
            <mesh >
              <boxBufferGeometry args={[4, 6, 0.2]} />
          
              <meshStandardMaterial color='#5af7e3'metalness={0.5} />
              
            </mesh>
            {!prev?  <mesh position={[0, 2.2, 0.1]} >
              <boxBufferGeometry args={[3.5, 1, 0.2]} />
              <meshStandardMaterial color="green" />
              <Text3D font={fontUrl} position={[-0.6,-0.3,0.12]} scale={0.5} >0000</Text3D>
            </mesh> :
            <mesh position={[0, 2.2, 0.1]} >
              <boxBufferGeometry args={[3.5, 1, 0.2]} />
              <meshStandardMaterial color="green" />
              <Text3D font={fontUrl} position={[-0.4,-0.3,0.12]} scale={0.5} >{result? result : prev+operator+current}
              <meshStandardMaterial color="yellow" />
              </Text3D>
            </mesh>}
            <mesh position={[-1.4, 1.1, 0.1]} onClick={()=>{reset()}} ref={ref}>
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]}  fontSize={0.2} color="white" >Clear</Text>
            </mesh>
            <mesh position={[-0.50, 1.1, 0.1]} onClick={()=>{calculate()}} >
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
               <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >=</Text>
            </mesh>
            <mesh position={[0.43, 1.1, 0.1]} onClick={()=>{handleOperator("/")}} >
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >/</Text>
            </mesh>
            <mesh position={[1.4, 1.1, 0.1]} onClick={()=>{handleOperator("*")}} >
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >*</Text>
            </mesh>
            <mesh position={[-1.4, 0.2, 0.1]} onClick={()=>{handleInput(7)}}>
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >7</Text>
            </mesh>
            <mesh position={[-0.50, 0.2, 0.1]} onClick={()=>{handleInput(8)}}>
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >8</Text>
            </mesh>
            <mesh position={[0.43, 0.2, 0.1]} onClick={()=>{handleInput(9)}}>
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >9</Text>
            </mesh>
            <mesh position={[1.4, 0.2, 0.1]} onClick={()=>{handleOperator("-")}}>
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >-</Text>
            </mesh>
              <mesh position={[-1.4, -0.7, 0.1]} onClick={()=>{handleInput(4)}}>
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >4</Text>
            </mesh>
            <mesh position={[-0.50, -0.7, 0.1]} onClick={()=>{handleInput(5)}}>
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >5</Text>
            </mesh>
            <mesh position={[0.43, -0.7, 0.1]} onClick={()=>{handleInput(6)}}>
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >6</Text>
            </mesh>
            <mesh position={[1.4, -0.7, 0.1]}onClick={()=>{handleOperator("+")}} >
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >+</Text>
            </mesh>
            <mesh position={[-1.4, -1.6, 0.1]} onClick={()=>{handleInput(1)}}>
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >1</Text>
            </mesh>
            <mesh position={[-0.50, -1.6, 0.1]}onClick={()=>{handleInput(2)}} >
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >2</Text>
            </mesh>
            <mesh position={[0.43, -1.6, 0.1]}onClick={()=>{handleInput(3)}} >
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >3</Text>
            </mesh>
            <mesh position={[1.4, -2.04, 0.1]} onClick={()=> {calculate()}} >
              <boxBufferGeometry args={[0.7, 1.6, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.2} color="white" >enter</Text>
            </mesh>
            <mesh position={[-0.95, -2.5, 0.1]} onClick={()=>{handleInput(0)}}>
              <boxBufferGeometry args={[1.6, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >0</Text>
            </mesh>
      
            <mesh position={[0.43, -2.5, 0.1]} onClick={()=>{handleInput(".")}} >
              <boxBufferGeometry args={[0.7, 0.7, 0.2]} />
              <meshStandardMaterial color="black" />
              <Text  position={[0,-0.08,0.12]} fontSize={0.3} color="white" >.</Text>
            </mesh>
          </Suspense>
        </Canvas>
      </main>
    </>
  )
}
